name: rpg_o_matic
description: "RPG-O-Matic - Ein Charaktergenerator für mehrere RPG Systeme."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.12.2

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  google_fonts: ^6.2.1
  provider: ^6.1.2
  path_provider: ^2.1.5
  file_picker: ^8.1.7
  pdf: ^3.11.2
  printing: ^5.13.4
  share_plus: ^10.1.4
  uuid: ^4.5.1
  desktop_drop: ^0.7.1
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  xml: ^7.0.1
dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/theme/
    - assets/plandata/